services:
  - type: web
    name: workfinder
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd py && gunicorn App:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9